[package]
name = "litaudio"
version = "0.1.0"
authors = ["Egor Dmitriev <egordmitriev2@gmail.com>"]
edition = "2018"

[dependencies]
litcontainers = { path = "../litcontainers/litcontainers" }
litcontainers_derive = { path = "../litcontainers/litcontainers_derive" }
num-traits = "0.2"